export * from './types';
export * from './hex';
export * from './rng';
export { buildTiles, tileType, tileLabel, isPureSea, hasSeaEdge, hasLandEdge, validateTiles } from './map';
export type { MapSpec, TileSpec, MountainSpec } from './map';
export * from './query';
export { createGame, allianceSeatCounts, STATE_VERSION } from './setup';
export { applyAction, applyActionInPlace, advance, getPendingDecision, isGameOver, cloneState, ACTIONS_FOR_DECISION } from './machine';
export { computeAllianceOrder, interleavedOrder, sequentialOrder } from './rules/turnOrder';
export { checkAllocation, emptyAllocation, rawCostOf } from './rules/allocation';
export type { AllocationCheck } from './rules/allocation';
export { legalFarmerTiles, legalShipTiles, legalSoldierTiles, checkBuildingPlacements, farmerLandReach, farmerSeaReach } from './rules/deploy';
export { movableUnitsAt, destinationsFrom, legalDestinations, orderableSourceTiles, validateOrder, isShipPhase } from './rules/movement';
export type { Destination } from './rules/movement';
export { defenderBonusPerSoldier, finalControl, retreatOptions, shipsLostWithSoldiers } from './rules/combat';
export { electGeneral, playedValue } from './rules/politics';
export { computeScores, rankScoreLines, compareScoreLines, tiedAtTop } from './rules/scoring';
export { roleOptions } from './flowSetup';
export { subPhaseName } from './flowMilitary';
