import type { MapSpec, TileSpec } from '../engine/map';
import type { FactionDef } from '../engine/types';

/**
 * The Claremont Colleges (decision 110), generated by scripts/genClaremont.ts
 * from the campus map: a landlocked six-player board where each college is a
 * faction. The alliances are the athletic conferences: Black = the Stags (CMC,
 * royal, and Harvey Mudd), White = the Sagehens (Pomona, royal, and Pitzer),
 * Green = Scripps (royal) and CGU. Neutral ground is the Consortium, north
 * Pomona and the athletic fields. Every college's home ground has the same
 * number of wheat and raw-material tiles.
 * Rows are [q, r, ground (college letter or n), resources (w wheat, t wood, s stone,
 * i iron), city?, starting faction?]. Each college's ground is tinted in its colours.
 */
type Row = [number, number, string, string, string?, string?, boolean?];

const TINTS: Record<string, string> = {
  C: '#cfa3a8', // CMC maroon
  M: '#e9d596', // Harvey Mudd gold
  P: '#a8bfdf', // Pomona blue
  Z: '#f3c49a', // Pitzer orange
  S: '#a9ccb4', // Scripps green
  G: '#e8aaa8', // CGU red
};

const ROWS: Row[] = [
  [2, -1, 'G', 'ws'],
  [3, -1, 'G', ''],
  [4, -2, 'M', ''],
  [5, -2, 'M', '', "Hoch-Shanahan", 'black-orange'],
  [6, -3, 'M', 'w'],
  [7, -3, 'M', 'w'],
  [8, -4, 'M', '', "Platt", 'black-orange'],
  [9, -4, 'M', ''],
  [10, -5, 'Z', ''],
  [11, -5, 'Z', ''],
  [12, -6, 'Z', 'wt'],
  [13, -6, 'Z', ''],
  [2, 0, 'G', '', "Harper Hall", 'green-rose'],
  [3, 0, 'G', 'w'],
  [4, -1, 'M', ''],
  [5, -1, 'M', 'ws'],
  [6, -2, 'M', 'iw'],
  [7, -2, 'M', ''],
  [8, -3, 'M', 'wt'],
  [9, -3, 'M', ''],
  [10, -4, 'Z', ''],
  [11, -4, 'Z', '', "McConnell", 'white-crimson'],
  [12, -5, 'Z', ''],
  [13, -5, 'Z', ''],
  [2, 1, 'G', 'w'],
  [3, 1, 'G', 'w'],
  [4, 0, 'S', ''],
  [5, 0, 'S', ''],
  [6, -1, 'S', ''],
  [7, -1, 'S', 'w'],
  [8, -2, 'S', ''],
  [9, -2, 'S', ''],
  [10, -3, 'Z', 'ws'],
  [11, -3, 'Z', 'w'],
  [12, -4, 'Z', ''],
  [13, -4, 'Z', 'w'],
  [2, 2, 'G', '', "Stauffer"],
  [3, 2, 'G', ''],
  [4, 1, 'S', ''],
  [5, 1, 'S', ''],
  [6, 0, 'S', 'ws'],
  [7, 0, 'S', 'wt'],
  [8, -1, 'S', 'w'],
  [9, -1, 'S', 'wi'],
  [10, -2, 'Z', ''],
  [11, -2, 'Z', 'w'],
  [12, -3, 'Z', '', "Mead Hall", 'white-crimson'],
  [13, -3, 'n', ''],
  [2, 3, 'G', 'iw'],
  [3, 3, 'G', '', "Burkle", 'green-rose'],
  [4, 2, 'n', 'wt'],
  [5, 2, 'S', 'w'],
  [6, 1, 'S', '', "Malott Commons", 'green-purple'],
  [7, 1, 'S', ''],
  [8, 0, 'S', '', "Denison Library", 'green-purple'],
  [9, 0, 'S', ''],
  [10, -1, 'Z', ''],
  [11, -1, 'Z', 'wt'],
  [12, -2, 'n', 'i'],
  [13, -2, 'n', '', "Grove House"],
  [2, 4, 'G', ''],
  [3, 4, 'G', ''],
  [4, 3, 'n', ''],
  [5, 3, 'n', ''],
  [6, 2, 'C', ''],
  [7, 2, 'C', ''],
  [8, 1, 'C', ''],
  [9, 1, 'C', ''],
  [10, 0, 'C', 'w'],
  [11, 0, 'C', ''],
  [12, -1, 'n', ''],
  [13, -1, 'n', ''],
  [2, 5, 'n', 'w'],
  [3, 5, 'n', 't'],
  [4, 4, 'n', '', "Honnold Library"],
  [5, 4, 'n', 'ws'],
  [6, 3, 'n', ''],
  [7, 3, 'C', '', "The Ath", 'black-purple'],
  [8, 2, 'C', ''],
  [9, 2, 'C', 'w'],
  [10, 1, 'C', '', "Collins", 'black-purple'],
  [11, 1, 'C', ''],
  [12, 0, 'n', '', "Keck Science"],
  [13, 0, 'n', 'w'],
  [0, 7, 'n', 'ws'],
  [1, 7, 'n', ''],
  [2, 6, 'n', '', "Huntley Bookstore"],
  [3, 6, 'n', ''],
  [4, 5, 'n', 'w'],
  [5, 5, 'n', ''],
  [6, 4, 'n', ''],
  [7, 4, 'C', ''],
  [8, 3, 'C', ''],
  [9, 3, 'C', ''],
  [10, 2, 'C', 'i'],
  [11, 2, 'n', ''],
  [12, 1, 'n', 'w'],
  [13, 1, 'n', 'ws'],
  [0, 8, 'n', ''],
  [1, 8, 'n', ''],
  [2, 7, 'n', ''],
  [3, 7, 'n', 'wi'],
  [4, 6, 'n', 'w'],
  [5, 6, 'n', ''],
  [6, 5, 'n', ''],
  [7, 5, 'n', 'wt'],
  [8, 4, 'C', ''],
  [9, 4, 'n', ''],
  [10, 3, 'n', 'w'],
  [11, 3, 'n', ''],
  [12, 2, 'n', 'wi'],
  [13, 2, 'n', ''],
  [0, 9, 'n', ''],
  [1, 9, 'n', ''],
  [2, 8, 'n', ''],
  [3, 8, 'n', ''],
  [4, 7, 'n', ''],
  [5, 7, 'n', '', "Bridges Auditorium"],
  [6, 6, 'n', ''],
  [7, 6, 'n', ''],
  [8, 5, 'n', ''],
  [9, 5, 'n', ''],
  [10, 4, 'n', '', "Zinda Field"],
  [11, 4, 'n', ''],
  [12, 3, 'n', '', "Roberts Pavilion"],
  [13, 3, 'n', ''],
  [0, 10, 'n', ''],
  [1, 10, 'P', 'ws'],
  [2, 9, 'P', ''],
  [3, 9, 'P', ''],
  [4, 8, 'P', 'w'],
  [5, 8, 'P', ''],
  [6, 7, 'n', ''],
  [7, 7, 'n', 'wt'],
  [8, 6, 'n', ''],
  [9, 6, 'n', ''],
  [10, 5, 'n', 'w'],
  [12, 4, 'n', ''],
  [0, 11, 'n', ''],
  [1, 11, 'P', ''],
  [2, 10, 'P', '', "Frary", 'white-purple'],
  [3, 10, 'P', ''],
  [4, 9, 'P', ''],
  [5, 9, 'P', ''],
  [6, 8, 'n', 'w'],
  [7, 8, 'n', ''],
  [8, 7, 'n', ''],
  [9, 7, 'n', ''],
  [0, 12, 'n', ''],
  [1, 12, 'P', ''],
  [2, 11, 'P', 'i'],
  [3, 11, 'P', 'w'],
  [4, 10, 'P', ''],
  [5, 10, 'n', ''],
  [6, 9, 'n', ''],
  [7, 9, 'n', '', "Merritt Field"],
  [8, 8, 'n', ''],
  [9, 8, 'n', ''],
  [0, 13, 'n', ''],
  [1, 13, 'n', ''],
  [2, 12, 'P', ''],
  [3, 12, 'P', ''],
  [4, 11, 'P', '', "Frank", 'white-purple'],
  [5, 11, 'n', ''],
  [6, 10, 'n', 'wt'],
  [7, 10, 'n', ''],
  [8, 9, 'n', ''],
  [9, 9, 'n', ''],
  [0, 14, 'n', ''],
  [2, 13, 'n', ''],
  [4, 12, 'n', 'w'],
  [6, 11, 'n', ''],
  [8, 10, 'n', ''],
  [10, 9, 'n', ''],
];

function build(): MapSpec {
  const tiles: TileSpec[] = ROWS.map(([q, r, ground, res, city, slot, walls]) => {
    const resources: NonNullable<TileSpec['resources']> = [];
    for (const ch of res) resources.push(({ w: 'wheat', t: 'wood', s: 'stone', i: 'iron' } as const)[ch as 'w']);
    const t: TileSpec = { q, r, base: 'auto', seaEdges: [], resources };
    if (TINTS[ground]) t.tint = TINTS[ground];
    if (city) t.city = { name: city, slot: slot ?? 'neutral', ...(walls ? { walls: true } : {}) };
    return t;
  });
  return { id: 'claremont', name: 'The Claremont Colleges', tiles, mountains: [] };
}

export const CLAREMONT_MAP: MapSpec = build();

/** starting cities are keyed by faction id already */
export const CLAREMONT_SLOTS: Record<string, string> = {};

/** the six colleges replace the usual faction names and colours on this map */
export const CLAREMONT_FACTIONS: FactionDef[] = [
  { id: 'black-purple', allianceId: 'black', name: 'CMC', color: '#8a1538', royal: true },
  { id: 'black-orange', allianceId: 'black', name: 'Harvey Mudd', color: '#e0a100', royal: false },
  { id: 'white-purple', allianceId: 'white', name: 'Pomona', color: '#1f4e9c', royal: true },
  { id: 'white-crimson', allianceId: 'white', name: 'Pitzer', color: '#f47b20', royal: false },
  { id: 'green-purple', allianceId: 'green', name: 'Scripps', color: '#3f7f5f', royal: true },
  { id: 'green-rose', allianceId: 'green', name: 'CGU', color: '#c8102e', royal: false },
];
